version: '3.8'

services:
  db:
    build: .
    container_name: science_periodic_db
    environment:
        POSTGRES_DB: science_periodic
        POSTGRES_USER: science_periodic_user
        POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data

volumes:
  db_data: