-- Таблица JOBSТаблица JOBS
CREATE TABLE public."JOBS" (
	"JOB_ID" varchar(10) NOT NULL,
	"JOB_TITLE" varchar(35) NOT NULL,
	"MIN_SALARY" numeric(6) NULL,
	"MAX_SALARY" numeric(6) NULL,
	CONSTRAINT "JOB_ID_PK" PRIMARY KEY ("JOB_ID"),
	CONSTRAINT "JOB_TITLE_NN" CHECK (("JOB_TITLE" IS NOT NULL))
);

-- Таблица REGIONS
CREATE TABLE public."REGIONS" (
	"REGION_ID" numeric NOT NULL,
	"REGION_NAME" varchar(25) NULL,
	CONSTRAINT "REG_ID_PK" PRIMARY KEY ("REGION_ID")
);

-- Таблица COUNTRIES
CREATE TABLE public."COUNTRIES" (
	"COUNTRY_ID" bpchar(2) NOT NULL,
	"COUNTRY_NAME" varchar(40) NULL,
	"REGION_ID" numeric NULL,
	CONSTRAINT "COUNTRY_C_ID_PK" PRIMARY KEY ("COUNTRY_ID")
);

-- Таблица LOCATIONS
CREATE TABLE public."LOCATIONS" (
	"LOCATION_ID" numeric(4) NOT NULL,
	"STREET_ADDRESS" varchar(40) NULL,
	"POSTAL_CODE" varchar(12) NULL,
	"CITY" varchar(30) NOT NULL,
	"STATE_PROVINCE" varchar(25) NULL,
	"COUNTRY_ID" bpchar(2) NULL,
	CONSTRAINT "LOC_ID_PK" PRIMARY KEY ("LOCATION_ID")
);

-- Таблица DEPARTMENTS
CREATE TABLE public."DEPARTMENTS" (
	"DEPARTMENT_ID" numeric(4) NOT NULL,
	"DEPARTMENT_NAME" varchar(30) NOT NULL,
	"MANAGER_ID" numeric(6) NULL,
	"LOCATION_ID" numeric(4) NULL,
	CONSTRAINT "DEPT_ID_PK" PRIMARY KEY ("DEPARTMENT_ID")
);

-- Таблица EMPLOYEES
CREATE TABLE public."EMPLOYEES" (
	"EMPLOYEE_ID" numeric(6) NOT NULL,
	"FIRST_NAME" varchar(20) NULL,
	"LAST_NAME" varchar(25) NOT NULL,
	"EMAIL" varchar(25) NOT NULL,
	"PHONE_NUMBER" varchar(20) NULL,
	"HIRE_DATE" date NOT NULL,
	"JOB_ID" varchar(10) NOT NULL,
	"SALARY" numeric(8, 2) NULL,
	"COMMISSION_PCT" numeric(2, 2) NULL,
	"MANAGER_ID" numeric(6) NULL,
	"DEPARTMENT_ID" numeric(4) NULL,
	CONSTRAINT "EMP_EMAIL_UK" UNIQUE ("EMAIL"),
	CONSTRAINT "EMP_EMP_ID_PK" PRIMARY KEY ("EMPLOYEE_ID"),
	CONSTRAINT "EMP_SALARY_MIN" CHECK (("SALARY" > (0)::numeric))
);

-- Таблица JOB_HISTORY
CREATE TABLE public."JOB_HISTORY" (
	"EMPLOYEE_ID" numeric(6) NOT NULL,
	"START_DATE" date NOT NULL,
	"END_DATE" date NOT NULL,
	"JOB_ID" varchar(10) NOT NULL,
	"DEPARTMENT_ID" numeric(4) NULL,
	CONSTRAINT "JHIST_DATE_INTERVAL" CHECK (("END_DATE" > "START_DATE")),
	CONSTRAINT "JHIST_EMP_ID_ST_DATE_PK" PRIMARY KEY ("EMPLOYEE_ID", "START_DATE")
);