-- COUNTRIES
ALTER TABLE public."COUNTRIES" ADD CONSTRAINT "COUNTR_REG_FK" FOREIGN KEY ("REGION_ID") REFERENCES public."REGIONS"("REGION_ID");

-- LOCATIONS
ALTER TABLE public."LOCATIONS" ADD CONSTRAINT "LOC_C_ID_FK" FOREIGN KEY ("COUNTRY_ID") REFERENCES public."COUNTRIES"("COUNTRY_ID");

-- DEPARTMENTS
ALTER TABLE public."DEPARTMENTS" ADD CONSTRAINT "DEPT_LOC_FK" FOREIGN KEY ("LOCATION_ID") REFERENCES public."LOCATIONS"("LOCATION_ID");
ALTER TABLE public."DEPARTMENTS" ADD CONSTRAINT "DEPT_MGR_FK" FOREIGN KEY ("MANAGER_ID") REFERENCES public."EMPLOYEES"("EMPLOYEE_ID");

-- EMPLOYEES
ALTER TABLE public."EMPLOYEES" ADD CONSTRAINT "EMP_DEPT_FK" FOREIGN KEY ("DEPARTMENT_ID") REFERENCES public."DEPARTMENTS"("DEPARTMENT_ID");
ALTER TABLE public."EMPLOYEES" ADD CONSTRAINT "EMP_JOB_FK" FOREIGN KEY ("JOB_ID") REFERENCES public."JOBS"("JOB_ID");
ALTER TABLE public."EMPLOYEES" ADD CONSTRAINT "EMP_MANAGER_FK" FOREIGN KEY ("MANAGER_ID") REFERENCES public."EMPLOYEES"("EMPLOYEE_ID");