version: '3.8'

services:
  db:
    build: .
    container_name: hr_db
    environment:
        POSTGRES_DB: hr
        POSTGRES_USER: hr_user
        POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data

volumes:
  db_data: